In [2]:
## read in important libraries 
import pandas as pd
import numpy as np
import sklearn as skl
from sklearn import preprocessing
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', None)

In [3]:
## example of reading in one of our datasets 
### Read in the base FIPS code dataset and drop Puerto Rico 

#FIPS_codes=pd.read_csv('../data/FIPS.csv', usecols=['FIPS','County','State','Merge'])
url = 'https://raw.githubusercontent.com/community-insight-impact/covid_community_vulnerability/master/data/FIPS.csv'
FIPS_codes = pd.read_csv(url, usecols=['FIPS','County','State','Merge'])
FIPS_codes=FIPS_codes[FIPS_codes['State']!='Puerto Rico']
#FIPS_codes['FIPS']=FIPS_codes['FIPS'].apply(fips_zeros)
FIPS_codes.head()

   FIPS    State          County                   Merge
0  1001  Alabama  Autauga County  Alabama Autauga County
1  1003  Alabama  Baldwin County  Alabama Baldwin County
2  1005  Alabama  Barbour County  Alabama Barbour County
3  1007  Alabama     Bibb County     Alabama Bibb County
4  1009  Alabama   Blount County   Alabama Blount County

State abbreviations by using a dictionary

In [ ]:
us_state_abbrev = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'American Samoa': 'AS',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'District of Columbia': 'DC',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Guam': 'GU',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Northern Mariana Islands':'MP',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Puerto Rico': 'PR',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virgin Islands': 'VI',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY'
}

abbrev_us_state = dict(map(reversed, us_state_abbrev.items()))